version: "3"
services:
  stats_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile
    entrypoint: "./docker-entrypoint-dev"
    working_dir: /application
    volumes:
      - .:/application
    networks:
      proxy:
        ipv4_address: 10.200.24.3

  stats_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - stats_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.stats_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.stats_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.24.2

networks:
  proxy:
    external: true
